# Generated by Django 2.2.7 on 2019-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodDatabase',
            fields=[
                ('prodId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=240, verbose_name='prodName')),
                ('prodDescription', models.CharField(max_length=1024)),
                ('prodPrice', models.CharField(max_length=20, verbose_name='prodPrice')),
                ('prodBatch', models.CharField(max_length=20)),
                ('expiryDate', models.CharField(max_length=20, verbose_name='expiryDate')),
                ('isAvailable', models.BooleanField(default=True)),
                ('isPrescriptionRequired', models.BooleanField(default=False)),
            ],
        ),
    ]
