# Generated by Django 2.2.7 on 2019-11-29 13:47

from django.db import migrations

def create_data(apps, schema_editor):
    prodDatabase = apps.get_model('product', 'prodDatabase')
    prodDatabase(
        prodName="Dolo", 
        prodDescription="this cures fever",
        prodPrice="6",
        prodBatch="HI8RE98J",
        expiryDate="25-10-2024",
        isAvailable=True,
        isPrescriptionRequired=False
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
    ]
