# Generated by Django 3.2.10 on 2022-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220223_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(default=0, max_length=10)),
                ('orderDate', models.CharField(default='', max_length=10)),
                ('deliveryDate', models.CharField(default='', max_length=10)),
                ('orderStatus', models.CharField(default='', max_length=15)),
                ('noOfItems', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
